const LESSONS = [
{id:'earbuds',title:'耳机 · 从询盘到成交',short:'耳机',subtitle:'询盘与谈判',category:'01 / EARBUDS · NEGOTIATION',buyer:'Dubai buyer',role:'迪拜 · 消费电子零售商（模拟）',rounds:[
{title:'了解需求',q:'We’re looking for wireless earbuds for our stores in Dubai. Could you introduce your products and tell me your minimum order quantity?',zh:'我们正在为迪拜门店采购无线耳机。请介绍产品，并说明最低起订量。',goals:['介绍你供应的产品','明确最低起订量及单位','追问客户需要的耳机类型'],keys:[['介绍耳机',/earbuds|earphones|headphones/i],['说明起订量',/MOQ|minimum|20,?000|twenty thousand/i],['询问需求',/what|which|looking for|prefer|requirements/i]],model:'Thank you for your interest in our products. We offer HTC headphones, earbuds, and speakers. Our MOQ for custom orders is 20,000 units. What type of earbuds are you looking for?',hint:'We offer… Our MOQ is… What type of…?',phrase:'What type of earbuds are you looking for?',phraseZh:'您在寻找哪种类型的耳机？',tip:'先回应客户已经说过的需求，再追问细节。品牌和起订量请替换成你实际有权销售的品牌和公司政策。'},
{title:'确认定制',q:'We’re interested in noise-cancelling earbuds. Can you add our logo to the packaging?',zh:'我们对降噪耳机感兴趣。包装上可以加我们的标志吗？',goals:['明确能否定制包装','请客户提供 logo 文件'],keys:[['回应定制需求',/custom|logo|branding/i],['索要文件',/send|share|provide/i]],model:'Yes, we can customize the packaging with your logo. Could you please send us your logo file and packaging requirements?',hint:'Yes, we can customize… Could you please send us…?',phrase:'Could you please send us your logo file?',phraseZh:'可以请您发一下标志文件吗？',tip:'offer customization 是“提供定制服务”。确认包装要求后，再核实费用和生产时间。'},
{title:'提供替代方案',q:'Twenty thousand units is too high for our first order. Could we start with five thousand units as a trial order?',zh:'首单两万件太多了。我们可以先采购五千件试单吗？',goals:['说明五千件的定制限制','给出现货替代方案'],keys:[['说明定制限制',/can.t|cannot|unable|not.*custom|custom.*not|minimum/i],['提供现货替代',/stock|ready.made|standard models/i]],model:'Unfortunately, we can’t offer customization for 5,000 units. However, you could consider our in-stock products. Please take a look at our catalog and let us know which models interest you.',hint:'Unfortunately, we can’t… However, you could consider…',phrase:'You could consider our in-stock products.',phraseZh:'您可以考虑我们的现货产品。',tip:'拒绝某个条件后给出可行替代，让客户有下一步选择。'},
{title:'推荐与交期',q:'Which wireless earbuds would you recommend, and how soon can you ship 5,000 units?',zh:'你推荐哪款无线耳机？五千件最快多久能发货？',goals:['推荐 NE21 并说明理由','回应发货时间，不确定就说明需要核实'],keys:[['推荐型号',/NE\s?21/i],['回应交期',/days|weeks|shipping date|lead time|confirm.*(stock|ship)|check.*(stock|ship)/i]],model:'I recommend the NE21. It’s a popular model. Let me confirm stock availability and the shipping date for 5,000 units. Do you have a freight forwarder in China?',hint:'I recommend… Let me confirm stock availability and…',phrase:'Let me confirm stock availability.',phraseZh:'让我确认一下库存情况。',tip:'客户问了产品和交期，两个都要回答。没有销售排名依据时，用 popular 比 best-selling 更稳妥。'},
{title:'准确报价',q:'Our freight forwarder is in Guangzhou. What’s your best EXW price for 5,000 units of the NE21?',zh:'我们的货代在广州。NE21 五千件，最优惠的 EXW 单价是多少？',goals:['说明五千件的报价','明确币种、单价和 EXW 条件'],keys:[['明确币种和金额',/\$\s?30|USD\s?30|US\s?\$?\s?30|thirty.*dollars|30.*dollars/i],['明确每件',/per unit|each|per piece/i],['明确贸易条件',/EXW/i]],model:'For 5,000 units, our EXW price is US$30 per unit.',hint:'For [quantity], our EXW price is [currency + amount] per unit.',phrase:'Our EXW price is US$30 per unit.',phraseZh:'我们的 EXW 单价为每件30美元。',tip:'价格不只是一串数字。报价时一并说明币种、单位和双方约定的贸易条件。'},
{title:'有条件让价',q:'US$30 is above our budget. Could you offer US$27 per unit for this trial order?',zh:'30美元超出预算。这次试单可以做到每件27美元吗？',goals:['把27美元与一万件挂钩','说明每件价格'],keys:[['提出数量条件',/10,?000|ten thousand|10k/i],['明确27美元报价',/27|twenty.seven/i]],model:'If you increase the order to 10,000 units, we can offer US$27 per unit.',hint:'If you increase the order to…, we can offer…',phrase:'If you increase the order to…',phraseZh:'如果您把订单数量提高到……',tip:'本场练习采用“数量换价格”。实际让价应符合公司授权，不必照搬示例金额。'},
{title:'促成首单',q:'We can only commit to 5,000 units for now. What’s the best price you can offer for that quantity?',zh:'我们目前只能订五千件。这个数量最低能做到什么价格？',goals:['说明五千件对应的29美元单价','表达建立长期合作的意愿'],keys:[['明确29美元',/29|twenty.nine/i],['表达合作意愿',/relationship|cooperation|long.term|work together/i]],model:'To build a long-term business relationship, we can offer US$29 per unit for 5,000 units.',hint:'To build a long-term business relationship, we can offer…',phrase:'To build a long-term business relationship…',phraseZh:'为了建立长期业务关系……',tip:'cooperation 是合作；corporation 是公司。明确这次让价适用的数量。'},
{title:'确认付款',q:'Could we pay a 30% deposit and the remaining 70% before shipment?',zh:'我们可以先付30%定金，剩余70%发货前支付吗？',goals:['明确是否接受本单付款条件','复述比例和尾款时间'],keys:[['确认30%定金',/30\s?%|thirty percent/i],['确认70%尾款',/70\s?%|seventy percent/i],['明确发货前',/before shipment|before shipping|prior to shipment/i]],model:'Yes, for this order, we can accept a 30% deposit by T/T and the remaining 70% before shipment.',hint:'For this order, we can accept… and the remaining…',phrase:'The remaining 70% before shipment.',phraseZh:'剩余70%在发货前付清。',tip:'练习设定为你获准接受这一方案。实际业务中，先核实审批，再确认变更后的付款条件。'},
{title:'发送形式发票',q:'Please send us a pro forma invoice for 5,000 units of the NE21 at US$29 per unit.',zh:'请发送形式发票：NE21，五千件，每件29美元。',goals:['说明附件为形式发票','请客户核对内容'],keys:[['说明形式发票',/\bPI\b|pro\s?forma invoice/i],['请客户核对',/review|check|confirm/i]],model:'Sure, please find the attached pro forma invoice for your review. Please check the product details, quantity, and payment terms.',hint:'Please find the attached… for your review.',phrase:'Please find the attached pro forma invoice.',phraseZh:'请查收附件中的形式发票。',tip:'只有实际附上文件时才用 attached。这里是口语演练，不会向客户发送任何文件。'},
{title:'明确备货时间',q:'When will the goods be ready after we pay the deposit?',zh:'我们付定金后多久能备好货？',goals:['说明约七天','明确从收到定金起算'],keys:[['说明七天',/seven|7/i],['明确起算点',/after.*(receive|deposit)|receipt.*deposit|once.*deposit/i]],model:'The goods will be ready about seven days after we receive your deposit. We’ll let you know as soon as it arrives.',hint:'The goods will be ready about… after we receive…',phrase:'After we receive your deposit.',phraseZh:'在我们收到定金之后。',tip:'“备好货”与“送达客户”不是同一时间。如果指工作日，明确说 working days。'}]},
{id:'phones',title:'手机 · 产品与采购需求',short:'手机',subtitle:'需求与产品介绍',category:'02 / SMARTPHONES · DISCOVERY',buyer:'Regional distributor',role:'中东 · 手机分销商（模拟）',rounds:[
{title:'了解采购需求',q:'We’re looking for smartphones for our retail business. Which models can you offer?',zh:'我们正在为零售业务采购手机。你们可以提供哪些型号？',goals:['说明可以推荐合适型号','询问目标价位和数量'],keys:[['询问预算',/budget|price range|target price/i],['询问数量',/quantity|quantities|how many|units/i]],model:'We can recommend suitable models for your market. Could you share your target price range and expected order quantity?',hint:'Could you share your target price range and…?',phrase:'What is your target price range?',phraseZh:'您的目标价位是多少？',tip:'先了解采购定位，再推荐型号，避免只堆砌配置。'},
{title:'确认配置',q:'We need good battery life and enough storage. What would you recommend?',zh:'我们需要续航好、存储空间充足的产品。你推荐什么？',goals:['追问存储容量','说明将核实电池规格'],keys:[['追问存储',/storage|128|256|capacity/i],['回应电池',/battery|battery life/i]],model:'What storage capacity do you need? I’ll check the available models and confirm their battery specifications before making a recommendation.',hint:'What storage capacity…? I’ll check…',phrase:'I’ll confirm the specifications.',phraseZh:'我会确认具体规格。',tip:'不编造续航小时数。区分电池容量、测试条件和实际使用时长。'},
{title:'核实兼容性',q:'Will these phones work with our local mobile networks?',zh:'这些手机能兼容我们当地的移动网络吗？',goals:['询问目标国家或运营商','说明要核实网络频段'],keys:[['询问当地信息',/country|countries|operator|carrier/i],['核实兼容',/bands|compatib|network.*check|check.*network/i]],model:'Which country and mobile operators are you targeting? We’ll check the supported network bands and confirm compatibility for the exact model.',hint:'Which country and mobile operators…? We’ll check…',phrase:'We’ll confirm compatibility for the exact model.',phraseZh:'我们会确认具体型号的兼容性。',tip:'中东并非单一市场。对具体国家、运营商和型号逐项确认，不做笼统保证。'},
{title:'样品与售后',q:'Can we test a sample first, and what warranty do you offer?',zh:'我们可以先测试样品吗？你们提供什么保修？',goals:['回应样品需求','回应保修并说明需确认条款'],keys:[['说明样品',/sample/i],['回应保修',/warranty|after.sales/i]],model:'We can check sample availability for you. I’ll also send you the warranty terms, including the coverage and claim process, for your review.',hint:'We can check sample availability… I’ll send you the warranty terms…',phrase:'I’ll send you the warranty terms for your review.',phraseZh:'我会把保修条款发给您查看。',tip:'客户问了样品和保修。不要只回应样品，也不要承诺未经确认的保修期限。'}]},
{id:'coffee',title:'咖啡机 · 演示与售后',short:'咖啡机',subtitle:'产品适配与售后',category:'03 / COFFEE MACHINES · CONSULTATION',buyer:'Hospitality buyer',role:'中东 · 酒店与办公设备采购（模拟）',rounds:[
{title:'确认使用场景',q:'We’re looking for coffee machines. Which model would you recommend?',zh:'我们想采购咖啡机。你推荐哪一款？',goals:['询问家庭、办公室或酒店用途','了解每天大约出杯量'],keys:[['了解使用场景',/home|office|hotel|caf[eé]|use.*where|where.*use/i],['了解出杯量',/cups|daily|per day/i]],model:'Will the machines be used at home, in offices, or in hotels? Approximately how many cups do you expect to serve each day?',hint:'Will the machines be used…? How many cups…?',phrase:'How many cups do you expect to serve each day?',phraseZh:'您预计每天需要供应多少杯？',tip:'先了解用途与工作量，再判断产品是否适合。'},
{title:'确认电气要求',q:'Can you supply machines suitable for our market?',zh:'你们能提供适合我们市场使用的机器吗？',goals:['询问目的地国家','核实电压与插头要求'],keys:[['询问国家',/country|destination|market.*which|which.*market/i],['核实电压',/voltage|volt/i],['核实插头',/plug/i]],model:'Which country will the machines be sold in? Please share the required voltage and plug type so we can confirm a suitable version.',hint:'Which country…? Please share the required voltage and plug type…',phrase:'Please confirm the voltage and plug type.',phraseZh:'请确认电压和插头类型。',tip:'不要把中东各国的电气要求视为一致。由具体市场需求决定版本。'},
{title:'操作与维护',q:'Are the machines easy to clean? Can you provide a demonstration?',zh:'机器容易清洁吗？你们能提供演示吗？',goals:['回应清洁问题','提供操作演示或说明书'],keys:[['回应清洁',/clean|maintenance/i],['回应演示',/demo|video|manual|demonstrat/i]],model:'I can send you the cleaning instructions and arrange a product demonstration. We can walk you through the daily cleaning steps for the model you choose.',hint:'I can send you… and arrange…',phrase:'We can walk you through the cleaning steps.',phraseZh:'我们可以为您逐步讲解清洁流程。',tip:'让客户看到实际步骤，比笼统承诺“非常容易”更有说服力。'},
{title:'处理故障咨询',q:'What happens if a machine stops working after delivery?',zh:'如果收货后机器出现故障怎么办？',goals:['了解问题并收集信息','核实保修后提供下一步'],keys:[['收集故障信息',/video|photos|serial|details|describe/i],['说明处理依据',/warranty|check|review/i]],model:'Please send us the serial number and a short video of the issue. We’ll review the problem and check the warranty coverage, then explain the next steps.',hint:'Please send us… We’ll review… then…',phrase:'We’ll explain the next steps.',phraseZh:'我们会说明后续处理步骤。',tip:'先收集信息并核实条款，再决定处理方案，避免先承诺无条件换新。'}]}
];
LESSONS.push(
{id:'bangladesh',title:'孟加拉 · 达卡采购模拟',short:'孟加拉',subtitle:'采购商情景模拟',category:'04 / BANGLADESH · BUYER SIMULATION',buyer:'Dhaka buyer',role:'达卡 · 电子产品采购商（模拟）',rounds:[
{title:'初次业务电话',q:'Hello, we distribute mobile accessories in Dhaka. Can you tell me about your earbuds and speakers?',zh:'你好，我们在达卡分销手机配件。可以介绍一下你们的耳机和音箱吗？',goals:['回应耳机与音箱需求','了解销售渠道或目标价格'],keys:[['回应产品类别',/earbuds|speakers/i],['了解采购定位',/price|budget|channel|online|retail/i]],model:'Thank you for reaching out. We offer earbuds and speakers. Do you mainly sell online or through retail stores? What is your target price range?',hint:'We offer… Do you mainly sell…? What is your target price range?',phrase:'Do you mainly sell online or through retail stores?',phraseZh:'您主要在线上销售，还是通过零售门店？',tip:'这是一个虚构采购情境，不代表所有孟加拉客户的采购习惯。根据这位客户的回答继续问。'},
{title:'预算与运费',q:'Our budget is US$12 per unit. Does your price include shipping to Bangladesh?',zh:'我们的预算是每件12美元。你们的价格包含到孟加拉的运费吗？',goals:['说明货价与运费是否分开','询问目的地和采购量'],keys:[['回应运费',/shipping|freight/i],['询问目的地',/destination|city|port|address/i],['询问数量',/quantity|units|how many/i]],model:'Our current quotation does not include shipping. Could you confirm the order quantity and destination city or port? We can then check the freight cost separately.',hint:'Our quotation does not include… Could you confirm…?',phrase:'We can check the freight cost separately.',phraseZh:'我们可以单独核实运费。',tip:'先说清楚报价包含什么，再核算运输。不要为了给出即时答复而猜测运费。'},
{title:'组合试单',q:'Could we place a trial order with two different models instead of ordering just one?',zh:'我们可以用两个不同型号组合试单，而不是只订一款吗？',goals:['询问每个型号的采购量','说明要核实库存和起订量'],keys:[['了解各型号数量',/quantity|quantities|how many/i],['核实库存或起订量',/stock|MOQ|minimum/i]],model:'Could you share the models and quantities you need for each? I’ll check stock availability and the minimum order quantity for each model before confirming the trial order.',hint:'Could you share the models and quantities…? I’ll check…',phrase:'What quantity do you need for each model?',phraseZh:'每个型号分别需要多少件？',tip:'组合订单要逐项确认型号与数量，避免把总数量误当成每款的起订量。'},
{title:'确认下一步',q:'Please send the quotation today. We’ll review it with our purchasing team tomorrow.',zh:'请今天发送报价，我们明天会和采购团队讨论。',goals:['明确报价发送安排','礼貌约定跟进时间'],keys:[['确认报价',/quotation|quote/i],['约定跟进',/follow.up|tomorrow|after.*review/i]],model:'Sure, I’ll send you the quotation today. May I follow up tomorrow after your team has reviewed it?',hint:'I’ll send you… May I follow up…?',phrase:'May I follow up after your team has reviewed it?',phraseZh:'您团队看过后，我可以再跟进一下吗？',tip:'按双方实际可执行的时间承诺。电话中有不清楚的数字，可以请对方再说一遍并书面确认。'}]},
{id:'middle-east',title:'中东 · 展会与客户会议',short:'中东',subtitle:'展会与会议模拟',category:'05 / MIDDLE EAST · MEETING SIMULATION',buyer:'Regional buyer',role:'中东 · 展会来访客户（模拟）',rounds:[
{title:'展会开场',q:'Hi, I noticed your coffee machines and headphones. What does your company specialize in?',zh:'你好，我看到你们的咖啡机和耳机。你们公司主要做什么产品？',goals:['简洁介绍三类产品','了解客户关注哪类产品'],keys:[['介绍产品',/phones|earbuds|headphones|coffee/i],['了解兴趣',/which|what.*interested|looking for/i]],model:'We supply smartphones, audio products, and coffee machines. Which product category are you most interested in for your market?',hint:'We supply… Which product category…?',phrase:'Which product category are you most interested in?',phraseZh:'您对哪类产品最感兴趣？',tip:'在展会先用两句话建立联系，随后围绕客户关注的产品展开。'},
{title:'确认目标市场',q:'We want to sell your products in several countries in the region. Can you support us?',zh:'我们想在该地区几个国家销售你们的产品。你们可以支持吗？',goals:['询问具体目标国家','核实各市场的产品和包装需求'],keys:[['询问国家',/countries|country|markets/i],['回应具体要求',/requirements|packaging|specifications/i]],model:'Which countries are you planning to sell in? Please share the product and packaging requirements for each market so we can check how we can support you.',hint:'Which countries…? Please share the requirements…',phrase:'Please share the requirements for each market.',phraseZh:'请提供各个市场的具体要求。',tip:'中东客户也有不同市场、渠道和目标。不要假设各国的产品版本、文件或包装需求完全相同。'},
{title:'处理独家代理请求',q:'If our first order goes well, can we become your exclusive distributor?',zh:'如果首单顺利，我们可以成为你们的独家代理吗？',goals:['表达愿意进一步探讨','询问区域和销售计划并保留审核'],keys:[['了解区域',/territory|market|region|country/i],['了解销售计划',/sales|plan|target|volume/i],['保留审核',/review|discuss|consider|evaluate/i]],model:'We’d be happy to discuss that. Could you share your proposed territory and sales plan? Our team would need to review the details before making any commitment.',hint:'We’d be happy to discuss… Our team would need to review…',phrase:'We would need to review the details first.',phraseZh:'我们需要先审核具体细节。',tip:'独家代理会影响长期业务安排。先收集区域、期限和目标等信息，再由公司审核，不在初次对话中直接承诺。'},
{title:'会议收尾',q:'This sounds promising. What should we do next?',zh:'听起来不错。下一步怎么推进？',goals:['说明将发送的资料','提出明确的后续会议安排'],keys:[['说明资料',/catalog|quotation|specifications|details/i],['明确跟进',/meeting|call|follow.up|schedule/i]],model:'I’ll send you the catalog and quotation for the models we discussed. Could we schedule a follow-up call next week after you’ve reviewed them?',hint:'I’ll send you… Could we schedule a follow-up call…?',phrase:'Could we schedule a follow-up call?',phraseZh:'我们可以安排一次后续电话沟通吗？',tip:'以“谁来做什么、什么时候完成”结束会议。确认具体时间时，也要确认双方时区。'}]}
);
